# Site settings
title: Sammenstilling
email: eyeversuseye@gmail.com
description: Data-driven animation in Norway
<<<<<<< HEAD
baseurl: "/sammenstilling/" # the subpath of your site, e.g. /blog/
=======
baseurl: "/sammenstilling" # the subpath of your site, e.g. /blog/
>>>>>>> gh-pages
url: "http://yratof.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:title/
twitter_username: yratof
github_username:  yratof
timezone: Europe/Oslo

collections:
  case-studies:
    output: true

# Extra things
exclude: ['node_modules']

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap